"""
Abstract Base Strategy

Defines the interface that ALL trading strategies must implement.
This ensures that the backtesting engine and live engine can consume
any strategy identically — strategies are interchangeable plugins.

To create a new strategy:
1. Subclass BaseStrategy
2. Implement prepare_data() — add indicators/pivots to the DataFrame
3. Implement generate_signals() — produce Signal objects for each bar
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, List
import pandas as pd


class TradeDirection(Enum):
    """Direction of a trade signal."""
    LONG = "LONG"
    SHORT = "SHORT"
    NONE = "NONE"


@dataclass
class Signal:
    """
    Represents a trading signal generated by a strategy.

    A Signal encapsulates everything the execution engine needs to
    enter and manage a trade: direction, trigger price, target, and stop loss.

    Attributes:
        direction: Whether this is a LONG, SHORT, or no-trade signal.
        trigger_price: The price at which to enter the trade.
        target_price: The take-profit price level.
        stop_loss_price: The stop-loss price level.
        timestamp: When this signal was generated.
        metadata: Additional strategy-specific data (e.g., pivot levels).
    """
    direction: TradeDirection = TradeDirection.NONE
    trigger_price: float = 0.0
    target_price: float = 0.0
    stop_loss_price: float = 0.0
    timestamp: Optional[pd.Timestamp] = None
    metadata: dict = field(default_factory=dict)

    @property
    def is_valid(self) -> bool:
        """A signal is valid if it has a direction and sensible prices."""
        return (
            self.direction != TradeDirection.NONE
            and self.trigger_price > 0
            and self.target_price > 0
            and self.stop_loss_price > 0
        )

    @property
    def risk_reward_ratio(self) -> float:
        """Calculate the risk:reward ratio of this signal."""
        if self.direction == TradeDirection.LONG:
            risk = self.trigger_price - self.stop_loss_price
            reward = self.target_price - self.trigger_price
        elif self.direction == TradeDirection.SHORT:
            risk = self.stop_loss_price - self.trigger_price
            reward = self.trigger_price - self.target_price
        else:
            return 0.0

        if risk <= 0:
            return 0.0
        return reward / risk


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Strategy Lifecycle:
    1. prepare_data(df) — Enrich raw OHLCV data with indicators/pivots
    2. generate_signals(df) — Produce a list of Signal objects

    The strategy should NOT manage position state, execute orders, or
    interact with the broker. It is purely analytical — it answers the
    question "given this data, what should I do?"
    """

    def __init__(self, name: str = "BaseStrategy"):
        """
        Initialize the strategy.

        Args:
            name: Human-readable name for logging and reports.
        """
        self.name = name

    @abstractmethod
    def prepare_data(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Enrich the raw OHLCV DataFrame with strategy-specific indicators.

        This is called ONCE before signal generation. Use it to calculate
        pivot points, moving averages, or any derived columns the strategy
        needs.

        Args:
            df: Raw OHLCV DataFrame with DateTimeIndex.

        Returns:
            The same DataFrame with additional indicator columns added.
        """
        pass

    @abstractmethod
    def generate_signals(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Generate trading signals for each bar in the DataFrame.

        This performs bar-by-bar analysis and populates signal columns.
        The returned DataFrame should have columns:
        - 'signal_direction': TradeDirection enum value (0=NONE, 1=LONG, 2=SHORT)
        - 'trigger_price': Entry trigger price
        - 'target_price': Take profit price
        - 'stop_loss_price': Stop loss price
        - 'is_reset': Whether this bar resets the strategy state (EOD)

        Args:
            df: DataFrame already enriched by prepare_data().

        Returns:
            DataFrame with signal columns added.
        """
        pass

    def get_signal_at(self, df: pd.DataFrame, index: int) -> Signal:
        """
        Extract a Signal object for a specific bar index.

        Convenience method to build a Signal from the DataFrame columns.

        Args:
            df: DataFrame with signal columns (output of generate_signals).
            index: Integer position index into the DataFrame.

        Returns:
            Signal object for that bar.
        """
        row = df.iloc[index]
        direction_val = int(row.get("signal_direction", 0))

        if direction_val == 1:
            direction = TradeDirection.LONG
        elif direction_val == 2:
            direction = TradeDirection.SHORT
        else:
            direction = TradeDirection.NONE

        return Signal(
            direction=direction,
            trigger_price=row.get("trigger_price", 0.0),
            target_price=row.get("target_price", 0.0),
            stop_loss_price=row.get("stop_loss_price", 0.0),
            timestamp=df.index[index],
        )
